package webProjects;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

import io.github.bonigarcia.wdm.WebDriverManager;

public class ClinicProfile {

	public static void main(String[] args) throws InterruptedException 
	{
		ChromeOptions opt=new ChromeOptions();
		opt.addArguments("---disable-notifications");
	    WebDriverManager.chromedriver().setup();
	  WebDriver driver = new ChromeDriver(opt);
	   driver.get("https://myclnq.co/stage/provider/#/");
	   driver.manage().window().maximize();
	   driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
	   driver.findElement(By.xpath("(//div[@class='role-box'])[1]")).click();
	   Thread.sleep(2000);
	   driver.findElement(By.xpath("//div[@class='selected-flag']")).click();
	   driver.findElement(By.xpath("//input[@class='search-box']")).sendKeys("india");
	   driver.findElement(By.xpath("//ul/li[@data-flag-key='flag_no_1']/span[text()='India']")).click();
	   driver.findElement(By.xpath("//input[@class='form-control text-control']")).sendKeys("8073798644");
	 driver.findElement(By.xpath("//button[@class='btn text-white continue ml-3 mt-2']")).click();
	 driver.findElement(By.xpath("(//input[@class='form-control me-3 otp-input-field'])[1]")).sendKeys("7");
	 driver.findElement(By.xpath("(//input[@class='form-control me-3 otp-input-field'])[2]")).sendKeys("2");
	 driver.findElement(By.xpath("(//input[@class='form-control me-3 otp-input-field'])[3]")).sendKeys("0");
	 driver.findElement(By.xpath("(//input[@class='form-control me-3 otp-input-field'])[4]")).sendKeys("7");
	 driver.findElement(By.xpath("//button[@class='btn text-white continue']")).click();
	 WebElement ele = driver.findElement(By.xpath("//*[@id=\"root\"]/div/div[2]/div/nav/div[1]/ul/li/div[6]/div/div"));
	 Thread.sleep(2000);
	 ele.click();
	 Thread.sleep(2000);
	 driver.findElement(By.xpath("//i[@class='ri-menu-line hamburger open-panel nav-toggle']")).click();
	 Thread.sleep(2000);
	 driver.findElement(By.xpath("//i[@class='ri-close-line hamburger open-panel nav-toggle']")).click();
	 Thread.sleep(2000);
	 driver.findElement(By.xpath("( //div[@class=' css-1xc3v61-indicatorContainer'])[2]")).click();
	 driver.findElement(By.xpath("//div[@class=' css-w32ibi-option']")).click();
	 Thread.sleep(2000);
	 WebElement cname = driver.findElement(By.xpath("//input[@placeholder='Clinic Name*']"));
	 Thread.sleep(2000);
	 cname.clear();
	 Thread.sleep(2000);
	 cname.sendKeys("Madhuhb");
	 WebElement Hreg = driver.findElement(By.xpath("//input[@placeholder='Hospital Registration Number*']"));
	 Thread.sleep(2000);
	 Hreg.clear();
	 Thread.sleep(2000);
	 Hreg.sendKeys("1234");
	 WebElement phoneno = driver.findElement(By.xpath("//input[@placeholder='Enter phone number*']"));
	 Thread.sleep(2000);
	 phoneno.clear();
	 Thread.sleep(2000);
	 phoneno.sendKeys("8073798644");
	 WebElement email = driver.findElement(By.xpath("//input[@placeholder='Email Address*']"));
	 Thread.sleep(2000);
	 email.clear();
	 Thread.sleep(2000);
	 email.sendKeys("hbmadhu13@gmail.com");
	 WebElement address = driver.findElement(By.xpath("//input[@placeholder='Clinic Address*']"));
	 Thread.sleep(2000);
	 address.clear();
	 Thread.sleep(2000);
	 address.sendKeys("Arekere,Bannerghatta");
	 WebElement zipcode = driver.findElement(By.xpath("//input[@placeholder='Zip Code*']"));
	 Thread.sleep(2000);
	 zipcode.clear();
	 Thread.sleep(2000);
	 zipcode.sendKeys("560076");
	 WebElement ele4 = driver.findElement(By.xpath("/html/body/div[3]/div[3]/div[2]/div[8]/div/button[2]"));
	 Thread.sleep(2000);
	 ele4.click();
	 Thread.sleep(2000);
	 driver.findElement(By.xpath("( //div[@class=' css-1xc3v61-indicatorContainer'])[2]")).click();
	 driver.findElement(By.xpath("(//div[@class=' css-1tdpez0-option'])[1]")).click();
	 Thread.sleep(2000);
	 WebElement ele5 = driver.findElement(By.xpath("(//input[@placeholder='HH:MM'])[2]"));
	 Thread.sleep(2000);
	 ele5.clear();
	 Thread.sleep(2000);
	 ele5.sendKeys("2326");
	 Thread.sleep(2000);
	 WebElement toggle2 = driver.findElement(By.xpath("(//div[@class='react-switch-bg'])[2]"));
	 Thread.sleep(2000);
	 toggle2.click();
	 Thread.sleep(2000);
	 toggle2.click();
	 WebElement toggle3 = driver.findElement(By.xpath("(//div[@class='react-switch-bg'])[3]"));
	 Thread.sleep(2000);
	 toggle3.click();
	 Thread.sleep(2000);
	 toggle3.click();
	 WebElement toggle4 = driver.findElement(By.xpath("(//div[@class='react-switch-bg'])[4]"));
	 Thread.sleep(2000);
	 toggle4.click();
	 Thread.sleep(2000);
	 toggle4.click();
	 WebElement toggle5 = driver.findElement(By.xpath("(//div[@class='react-switch-bg'])[5]"));
	 Thread.sleep(2000);
	 toggle5.click();
	 Thread.sleep(2000);
	 toggle5.click();
	 WebElement toggle6 = driver.findElement(By.xpath("(//div[@class='react-switch-bg'])[6]"));
	 Thread.sleep(2000);
	 toggle6.click();
	 Thread.sleep(2000);
	 toggle6.click();
	 WebElement toggle7 = driver.findElement(By.xpath("(//div[@class='react-switch-bg'])[7]"));
	 Thread.sleep(2000);
	 toggle7.click();
	 Thread.sleep(2000);
	 toggle7.click();
	 driver.findElement(By.xpath("//button[@class='btn dialog-btn dialog-btn-type-filled']")).click();
	 Thread.sleep(2000);
	 WebElement update = driver.findElement(By.xpath("//button[@class='dialog-btn dialog-btn-type-filled']"));
	 Thread.sleep(2000);
	 update.click();
	 Thread.sleep(2000);
	 driver.findElement(By.xpath("(//div[@class=' css-1wy0on6'])[2]")).click();
	Thread.sleep(2000);
	WebElement ele8 = driver.findElement(By.xpath("//div[text()='Edit Configuration']"));
	Thread.sleep(2000);
	ele8.click();
	WebElement ele9 = driver.findElement(By.xpath("/html/body/div[3]/div[3]/div[10]/button[2]"));
	Thread.sleep(2000);
	ele9.click();
	WebElement manageleave = driver.findElement(By.xpath("//button[@class='btn btn-outline-danger leave manage-leave mr-2']"));
	Thread.sleep(2000);
	manageleave.click();
	Thread.sleep(2000);
	WebElement leave = driver.findElement(By.xpath("(//div[@class='rmdp-day'])[3]"));
	Thread.sleep(2000);
	leave.click();
	Thread.sleep(2000);
	driver.findElement(By.id("exampleInputEmail1")).sendKeys("mmafds");
	Thread.sleep(2000);
	WebElement submit = driver.findElement(By.xpath("//button[text()='Submit']"));
	Thread.sleep(2000);
	submit.click();
	Thread.sleep(2000);
	WebElement dropdown1 = driver.findElement(By.xpath("(//button[@class='accordion-button collapsed'])[1]"));
	Thread.sleep(2000);
	dropdown1.click();
	Thread.sleep(2000);
	dropdown1.click();
	WebElement dropdown2 = driver.findElement(By.xpath("(//button[@class='accordion-button collapsed'])[2]"));
	Thread.sleep(2000);
	dropdown2.click();
	Thread.sleep(2000);
	dropdown2.click();
	WebElement dropdown3 = driver.findElement(By.xpath("(//button[@class='accordion-button collapsed'])[3]"));
	Thread.sleep(2000);
	dropdown3 .click();
	Thread.sleep(2000);
	dropdown3 .click();
	WebElement dropdown4 = driver.findElement(By.xpath("(//button[@class='accordion-button collapsed'])[4]"));
	Thread.sleep(2000);
	dropdown4 .click();
	Thread.sleep(2000);
	dropdown4 .click();
	
	}
}
