package webProjects;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

import io.github.bonigarcia.wdm.WebDriverManager;

public class ViewProfileDoctor {

	public static void main(String[] args) throws InterruptedException 
	{
		ChromeOptions opt=new ChromeOptions();
		opt.addArguments("---disable-notifications");
	    WebDriverManager.chromedriver().setup();
	  WebDriver driver = new ChromeDriver(opt);
	   driver.get("https://myclnq.co/stage/provider/#/");
	   driver.manage().window().maximize();
	   driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
	   driver.findElement(By.xpath("(//div[@class='role-box'])[1]")).click();
	   Thread.sleep(2000);
	   driver.findElement(By.xpath("//div[@class='selected-flag']")).click();
	   driver.findElement(By.xpath("//input[@class='search-box']")).sendKeys("india");
	   driver.findElement(By.xpath("//ul/li[@data-flag-key='flag_no_1']/span[text()='India']")).click();
	   driver.findElement(By.xpath("//input[@class='form-control text-control']")).sendKeys("8073798644");
	 driver.findElement(By.xpath("//button[@class='btn text-white continue ml-3 mt-2']")).click();
	 driver.findElement(By.xpath("(//input[@class='form-control me-3 otp-input-field'])[1]")).sendKeys("7");
	 driver.findElement(By.xpath("(//input[@class='form-control me-3 otp-input-field'])[2]")).sendKeys("2");
	 driver.findElement(By.xpath("(//input[@class='form-control me-3 otp-input-field'])[3]")).sendKeys("0");
	 driver.findElement(By.xpath("(//input[@class='form-control me-3 otp-input-field'])[4]")).sendKeys("7");
	 driver.findElement(By.xpath("//button[@class='btn text-white continue']")).click();
	 WebElement ele = driver.findElement(By.xpath("//*[@id=\"root\"]/div/div[2]/div/nav/div[1]/ul/li/div[4]"));
	 Thread.sleep(2000);
	 ele.click();
	 Thread.sleep(2000);
	 driver.findElement(By.xpath("//i[@class='ri-menu-line hamburger open-panel nav-toggle']")).click();
	 Thread.sleep(2000);
	 driver.findElement(By.xpath("//i[@class='ri-close-line hamburger open-panel nav-toggle']")).click();
	 Thread.sleep(2000);
	 WebElement ele3 = driver.findElement(By.xpath("(//button[@class='btn btn-sm btn-md btn-danger view-profile-button text-nowrap '])[1]"));
	 Thread.sleep(2000);
	 ele3.click();
	 driver.findElement(By.xpath("(//div[@class=' css-1xc3v61-indicatorContainer'])[2]")).click();
	 Thread.sleep(2000);
	 WebElement ele4 = driver.findElement(By.xpath("//div[text()='Edit Profile']"));
	 Thread.sleep(2000);
	 ele4.click();
	 Thread.sleep(2000);
	 WebElement ele5 = driver.findElement(By.xpath("/html/body/div[3]/div[3]/div/div[2]/div[13]/div[2]/button[2]"));
	 Thread.sleep(2000);
	 ele5.click();
	 Thread.sleep(2000);
	 driver.findElement(By.xpath("(//div[@class=' css-1xc3v61-indicatorContainer'])[2]")).click();
	 Thread.sleep(2000);
	 WebElement ele7 = driver.findElement(By.xpath("//div[text()='Edit Timing']"));
	 Thread.sleep(2000);
	 ele7.click();
	 driver.findElement(By.xpath("(//div[@class='react-switch-bg'])[1]")).click();
	 Thread.sleep(2000);
	 driver.findElement(By.xpath("(//div[@class='react-switch-bg'])[1]")).click();
	 Thread.sleep(2000);
	 driver.findElement(By.xpath("(//div[@class='react-switch-bg'])[13]")).click();
	 Thread.sleep(2000);
	 WebElement ele8 = driver.findElement(By.xpath("/html/body/div[3]/div[3]/div/div[8]/button[2]"));
	 Thread.sleep(2000);
	 ele8.click();
	 Thread.sleep(2000);
	 WebElement ele01 = driver.findElement(By.xpath("//button[text()='Update']"));
	 Thread.sleep(2000);
	 ele01.click();
	 Thread.sleep(2000);
	 WebElement ele02 = driver.findElement(By.xpath("//span[text()='Select vital signs']"));
	 Thread.sleep(2000);
	 ele02.click();
	 Thread.sleep(2000);
	 WebElement ele03 = driver.findElement(By.xpath("//button[text()='Submit']"));
	 Thread.sleep(2000);
	 ele03.click();
	 Thread.sleep(2000);
	 WebElement ele04 = driver.findElement(By.xpath("//span[text()='Manage Leave']"));
	 Thread.sleep(2000);
	 ele04.click();
	 Thread.sleep(2000);
	 WebElement ele05 = driver.findElement(By.xpath("(//div[@class='rmdp-day'])[4]"));
	 Thread.sleep(2000);
	 ele05.click();
	 Thread.sleep(2000);
	 WebElement ele06 = driver.findElement(By.xpath("/html/body/div/div[2]/div/div/header/i[2]"));
	 Thread.sleep(2000);
	 ele06.click();
	 Thread.sleep(2000);
	 WebElement ele07 = driver.findElement(By.xpath("(//button[@class='accordion-button collapsed'])[1]"));
	 Thread.sleep(2000);
	 ele07.click();
	 Thread.sleep(2000);
	 ele07.click();
	 Thread.sleep(2000);
	 WebElement ele08 = driver.findElement(By.xpath("(//button[@class='accordion-button collapsed'])[2]"));
	 Thread.sleep(2000);
	 ele08.click();
	 Thread.sleep(2000);
	 ele08.click();
	 Thread.sleep(2000);
	 WebElement ele09 = driver.findElement(By.xpath("(//button[@class='accordion-button collapsed'])[3]"));
	 Thread.sleep(2000);
	 ele09.click();
	 Thread.sleep(2000);
	 ele09.click();
	 Thread.sleep(2000);
	 WebElement ele001 = driver.findElement(By.xpath("(//button[@class='accordion-button collapsed'])[4]"));
	 Thread.sleep(2000);
	 ele001.click();
	 Thread.sleep(2000);
	 ele001.click();
	 Thread.sleep(2000);
	 WebElement ele002 = driver.findElement(By.xpath("(//button[@class='accordion-button collapsed'])[5]"));
	 Thread.sleep(2000);
	 ele002.click();
	 Thread.sleep(2000);
	 ele002.click();
	}
}
